config/routes.rb
Rpg::Application.routes.draw do

  resources :messages do
    member do
       get :deleta
    end
  end

   devise_for :users
   
   get 'planets/index'

   resources :squads do
     member do
       get :goal
       get :transfer
     end
   end

   resources :tradeports

   resources :generic_units do
     member do
       get :ships
     end
     collection do
       get :move
     end
   end

   resources :facilities do
     member do
       get :buy
     end
   end

   resources :planets, :shallow => true do
     resources :facility_fleets
     member do
       get :move
     end
     collection do
       get :map
     end
     resources :results do
       member do
         get :show_results
         get :show_fog
         get :calculate_troopers
         get :calculate_warriors
       end
     end
 
   end

   resources :generic_fleets do
     member do
       put :move
       put :move_facility
       get :sensor
       put :move_one_fleet
       put :arm
       put :disarm
     end
   end

   resources :capital_ships do
     member do
       put :load_in
       put :unload_from
       put :get_leadership
       put :install_skill
       put :uninstall_skill
     end
   end

   resources :light_transports do
     member do
       put :load_in
       put :unload_from
     end
   end

   resources :fighters do
     member do
     end
   end

   resources :sensors

   resources :settings

   match 'ready' => 'squads#ready'
   match 'index' => 'home#index'
   match 'fleets' => 'generic_fleets#index'
   match 'transfer' => 'squads#transfer'
   match 'close_popup' => 'home#close_popup'
   match 'back_to_main' => 'generic_fleets#back_to_main'

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => "Squad"
  belongs_to :receiver, :class_name => "Squad"
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.xml
  def index
    @current_squad = current_squad 
    @messages = Message.all
    @message = Message.new
    @squads = Squad.all.reject! { |squad| squad == @current_squad }
   

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message = Message.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.xml
  def create
    
    @message = Message.new(params[:message]) 
    
    respond_to do |format|
      if @message.save
        #format.html { redirect_to(@message, :notice => 'Message was successfully created.') }
        format.html { redirect_to :back }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        @format.html { redirect_to(@message, :notice => 'Message was successfully updated.') }
        format.html { redirect_to :back }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def deleta


    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to(messages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <br>
    <%= f.hidden_field :sender_id, :value => @current_squad.id %>

    <%= f.input :body, :label => false %><br>
    <%= f.association :receiver, :collection => @squads, :include_blank => "Todos", :label => 'Para:' %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div class="message_board">
<br>
<span style="font-size:28px">Message Board</span>

<%= render 'form' %>

<table style="border: 1px solid grey">
  <tr>
    <th style="text-align:center">De:</th>
    <th style="text-align:center">Para:</th>
    <th style="text-align:center">Data:</th>
    <th>Mensagem:</th>
    <th></th>
    <th></th>
  </tr>

<% @messages.reverse.each do |message| %>
  <% next if message.sender != @current_squad && ( message.receiver != nil && message.receiver != @current_squad ) %>
  <tr>
    <td style="text-align:center">
    <img src="/images/<%= message.sender.faction %>.png" height="25" width="25"><br>
    <span style="color:#<%= message.sender.color %>"><%= message.sender.name %></span></td>
    <% unless message.receiver.nil? %>
      <td style="text-align:center">
        <img src="/images/<%= message.receiver.faction %>.png" height="25" width="25"><br>
        <span style="color:#<%= message.receiver.color %>"><%= message.receiver.name %></span>
      </td>
    <% else %>
      <td style="vertical-align:middle;text-align:center"><%= 'Todos' %></td>
    <% end %>
    <td style="text-align:center"><%= message.created_at.strftime("%D, %l:%M%P") %></td>
    <td><%= message.body %></td>
    <td><%= link_to 'Edit', edit_message_path(message) if message.sender == @current_squad  %></td>
    <td><%= link_to 'Apagar', deleta_message_path(message) if message.sender == @current_squad  %></td>
  </tr>
<% end %>
</table>

<br />
</div>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sender:</b>
  <%= @message.sender %>
</p>

<p>
  <b>Receiver:</b>
  <%= @message.receiver %>
</p>

<p>
  <b>Title:</b>
  <%= @message.title %>
</p>

<p>
  <b>Body:</b>
  <%= @message.body %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>